### ISSUE TITLE
Explorer for Windowes 8.1 messes up images of different sizes

### ISSUE THREAD

**Issue by HansKy** [webbiesdk/SudoSlider#20] opened 2014-12-21 16:44 UTC
Hi Erik
Going from Version 3.2.0 to Version 3.3.2 I get into real trouble when I use Images of different dimensions. The problems appear only in Internet Explorer for Windows 8.1, but not in other Browsers with Windows 8.1. Version 3.2.0 on the other hand has no problems with Internet Explorer for Windows 8.1.
Could you check that?
Thanks and kind regards
Hans

**Comment by webbiesdk** [comment] 2015-01-07 14:09
Closing issue, not able to reproduce.

**Closed by webbiesdk** 2015-01-07 14:09 UTC
