### ISSUE TITLE
New firefox bug

### ISSUE THREAD

**Issue by sasovin** [webbiesdk/SudoSlider#56] opened 2016-05-20 07:15 UTC
Thank you for the solution https://github.com/webbiesdk/SudoSlider/issues/55, but now there was another problem. Right peeps 1 pixel of the next slide.
http://joxi.ru/BA0pneKsBxl44A
Perhaps in such cases needs to be done, for example, the width of the first visible slide as:
width_first_slide=Round(width_slide)+(width_window-Round(width_slide)*count_slide)
or similar.

**Comment by webbiesdk** [comment] 2016-05-20 13:21
Your proposal wouldn't quite work, as the problem isn't that the total width of all slides is to low. The problem is that the total widths of the visible slides is to low. 

So now, if i due to rounding remove 0.5 pixels from the width of each slide, i add an extra pixel to every 2nd slide. 
If you have continuous on, this might result in the slider being a single pixel to side in some cases, but this should change anything. 

I'll make a release of it once you confirm it has been fixed.

**Comment by sasovin** [comment] 2016-05-25 11:43
Hi!
Sorry, I did not answer for a long time.
Yes, in my version I had in mind the count of visible the slides (count_visible_slide). But it was an example.
Thank you for your correction, but sometimes when resize window, 1px still there. Strange, I do not understand what this has caused.
http://joxi.ru/52akN0LsGwJvlr

**Comment by sasovin** [comment] 2016-05-25 11:45
Hi!
Sorry, I did not answer for a long time.
Yes, in my version I had in mind the count of visible the slides (count_visible_slide). But it was an example.
Thank you for your correction, but sometimes when resize window, 1px still there. Strange, I do not understand what this has caused.
http://joxi.ru/52akN0LsGwJvlr

**Comment by sasovin** [comment] 2016-05-25 11:45
Hi!
Sorry, I did not answer for a long time.
Yes, in my version I had in mind the count of visible the slides (count_visible_slide). But it was an example.
Thank you for your correction, but sometimes when resize window, 1px still there. Strange, I do not understand what this has caused.
http://joxi.ru/52akN0LsGwJvlr

**Comment by webbiesdk** [comment] 2016-05-25 11:52
I just tried to replicate your screenshot in Firefox, didn't succeed. 

Try to clean your cache, so you are sure that you are using the latest version.

**Comment by sasovin** [comment] 2016-05-25 12:10
Cache clear.
Firefox latest version, 46.0.1
If at the time when there was an extra pixel, refresh the page, then everything is OK.
If only resize the window sometimes appears an extra pixel.

**Comment by webbiesdk** [comment] 2016-05-25 12:33
Ok, I missed the part where i had to resize it after a refresh. I can replicate it now. 

Looks like a bug in Firefox (without having debugged yet it that much yet), it seems like Firefox reports that the window width is 1022, while it is actually 1023 (or similar). 

I'll take a better look at it later.

**Comment by webbiesdk** [comment] 2016-05-26 19:00
It was a bug on my end, fixed now.

**Closed** 2016-05-26 18:59 UTC
